### [데이터 시각화 - 시도별전출입인구데이터]
- 엑셀파일 => DataFrame
-

[1] 모듈 로딩 및 데이터 준비

In [48]:
## 모듈 로딩
import pandas as pd
import matplotlib.pyplot as plt
import koreanize_matplotlib

In [49]:
## 데이터 준비
DATA_FILE = '../Data/시도별 전출입 인구수.xlsx'

## 엑셀 -> 데이터프레임 : opnepy    
dataDF = pd.read_excel(DATA_FILE)

In [50]:
display(dataDF.head())
dataDF.info()


## 기본적인 전처리 --------------------------------------------------
# -> 0번 행 삭제
# -> 전출지별 컬럼의 결측치 => 이전행의 값으로 채우기
# -> 70~ 17년 컬럼 데이터 object => int 
# -> 전출지별, 전입지별 => 행인덱스 사용 가능
# -> 결측치 컬럼 조재 => 1984, 1985, 1986 컬럼 3개
# -> 이상문자 '-' 거의 모든 컬럼에 존재
## ----------------------------------------------------------

,전출지별,전입지별,1970,1971,1972,1973,1974,1975,1976,1977,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,NaN,NaN,이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),...,이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명)
1,전국,전국,4046536,4210164,3687938,4860418,5297969,9011440,6773250,7397623,...,8808256,8487275,8226594,8127195,7506691,7411784,7629098,7755286,7378430,7154226
2,NaN,서울특별시,1742813,1671705,1349333,1831858,2050392,3396662,2756510,2893403,...,2025358,1873188,1733015,1721748,1555281,1520090,1573594,1589431,1515602,1472937
3,NaN,부산광역시,448577,389797,362202,482061,680984,805979,724664,785117,...,514502,519310,519334,508043,461042,478451,485710,507031,459015,439073
4,NaN,대구광역시,-,-,-,-,-,-,-,-,...,409938,398626,370817,370563,348642,351873,350213,351424,328228,321182

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 50 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   전출지별    18 non-null     object
 1   전입지별    324 non-null    object
 2   1970    325 non-null    object
 3   1971    325 non-null    object
 4   1972    325 non-null    object
 5   1973    325 non-null    object
 6   1974    325 non-null    object
 7   1975    325 non-null    object
 8   1976    325 non-null    object
 9   1977    325 non-null    object
 10  1978    325 non-null    object
 11  1979    325 non-null    object
 12  1980    325 non-null    object
 13  1981    325 non-null    object
 14  1982    325 non-null    object
 15  1983    325 non-null    object
 16  1984    322 non-null    object
 17  1985    322 non-null    object
 18  1986    322 non-null    object
 19  1987    325 non-null    object
 20  1988    325 non-null    object
 21  1989    325 non-null    object
 22  1990    325 non-null    object
 23  1991    325 non-null    object
 24  1992    325 non-null    object
 25  1993    325 non-null    object
 26  1994    325 non-null    object
 27  1995    325 non-null    object
 28  1996    325 non-null    object
 29  1997    325 non-null    object
 30  1998    325 non-null    object
 31  1999    325 non-null    object
 32  2000    325 non-null    object
 33  2001    325 non-null    object
 34  2002    325 non-null    object
 35  2003    325 non-null    object
 36  2004    325 non-null    object
 37  2005    325 non-null    object
 38  2006    325 non-null    object
 39  2007    325 non-null    object
 40  2008    325 non-null    object
 41  2009    325 non-null    object
 42  2010    325 non-null    object
 43  2011    325 non-null    object
 44  2012    325 non-null    object
 45  2013    325 non-null    object
 46  2014    325 non-null    object
 47  2015    325 non-null    object
 48  2016    325 non-null    object
 49  2017    325 non-null    object
dtypes: object(50)
memory usage: 127.1+ KB

[2] 전처리

In [51]:
## [2-1] 불필요 데이터 제거
# -> 0번 행 삭제
# -> 전출지별 컬럼의 결측치 => 이전행의 값을 채우기
dataDF2 = dataDF.copy()

dataDF2.drop(index=range(0,19), inplace=True)
dataDF2

,전출지별,전입지별,1970,1971,1972,1973,1974,1975,1976,1977,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
19,서울특별시,전국,1448985,1419016,1210559,1647268,1819660,2937093,2495620,2678007,...,2083352,1925452,1848038,1834806,1658928,1620640,1661425,1726687,1655859,1571423
20,NaN,서울특별시,1232619,1158556,985945,1345508,1511726,2401970,2041724,2212213,...,1426213,1286855,1199708,1215122,1069300,1053008,1098023,1129529,1061915,1018807
21,NaN,부산광역시,11568,11130,11768,16307,22220,27515,23732,27213,...,17353,17738,17418,18816,16135,16153,17320,17009,15062,14484
22,NaN,대구광역시,-,-,-,-,-,-,-,-,...,9720,10464,10277,10397,10135,10631,10062,10191,9623,8891
23,NaN,인천광역시,-,-,-,-,-,-,-,-,...,50493,45392,46082,51641,49640,47424,43212,44915,43745,40485
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,NaN,전라북도,139,202,141,210,219,415,392,408,...,668,579,672,561,551,516,609,683,733,768
321,NaN,전라남도,631,965,857,952,1133,2808,2608,2652,...,1143,1123,1002,1026,966,1001,928,1062,1127,1102
322,NaN,경상북도,374,619,468,576,625,1123,1141,1004,...,761,704,738,756,699,781,728,903,931,994
323,NaN,경상남도,474,479,440,571,1208,1517,863,1122,...,1517,1474,1324,1367,1227,1278,1223,1500,1448,1501
324,NaN,제주특별자치도,9290,12427,12210,16158,19580,34221,23291,31028,...,59564,55673,55507,59846,54280,60607,59673,59036,66444,63275

In [52]:
## -> 전출지별 컬럼의 결측치 -> 이전행의 값을 채우기 
dataDF.isna().sum()

dataDF2['전출지별'] = dataDF2['전출지별'].ffill()
dataDF2.isna().sum()

전출지별    0
전입지별    0
1970    0
1971    0
1972    0
1973    0
1974    0
1975    0
1976    0
1977    0
1978    0
1979    0
1980    0
1981    0
1982    0
1983    0
1984    3
1985    3
1986    3
1987    0
1988    0
1989    0
1990    0
1991    0
1992    0
1993    0
1994    0
1995    0
1996    0
1997    0
1998    0
1999    0
2000    0
2001    0
2002    0
2003    0
2004    0
2005    0
2006    0
2007    0
2008    0
2009    0
2010    0
2011    0
2012    0
2013    0
2014    0
2015    0
2016    0
2017    0
dtype: int64

In [53]:
# -> 결측치 컬럼 조재 => 1984, 1985, 1986 컬럼 3개 : 빈칸 => 0
pd.set_option('future.no_silent_downcasting', True)
dataDF2 = dataDF2.fillna(value=0)

# -> 이상문자 '-' 거의 모든 컬럼에 존재 : 없다 => 0
dataDF2=dataDF2.replace('-', 0)

In [54]:
## 기본 처리 후 체크
print(dataDF2.isna().sum())
print("------------------------------------------")
print(dataDF2[dataDF2=='-'].sum())

전출지별    0
전입지별    0
1970    0
1971    0
1972    0
1973    0
1974    0
1975    0
1976    0
1977    0
1978    0
1979    0
1980    0
1981    0
1982    0
1983    0
1984    0
1985    0
1986    0
1987    0
1988    0
1989    0
1990    0
1991    0
1992    0
1993    0
1994    0
1995    0
1996    0
1997    0
1998    0
1999    0
2000    0
2001    0
2002    0
2003    0
2004    0
2005    0
2006    0
2007    0
2008    0
2009    0
2010    0
2011    0
2012    0
2013    0
2014    0
2015    0
2016    0
2017    0
dtype: int64
------------------------------------------
전출지별    0
전입지별    0
1970    0
1971    0
1972    0
1973    0
1974    0
1975    0
1976    0
1977    0
1978    0
1979    0
1980    0
1981    0
1982    0
1983    0
1984    0
1985    0
1986    0
1987    0
1988    0
1989    0
1990    0
1991    0
1992    0
1993    0
1994    0
1995    0
1996    0
1997    0
1998    0
1999    0
2000    0
2001    0
2002    0
2003    0
2004    0
2005    0
2006    0
2007    0
2008    0
2009    0
2010    0
2011    0
2012    0
2013    0
2014    0
2015    0
2016    0
2017    0
dtype: object

[3] 서울 => 타지역으로 이주한 인구변화 시각화<hr>

In [ ]:
def getLocalDF(local_name, local_idx) :
    ## 서울 특별시 관련 데이터만 추출
    df = dataDF2[dataDF2['전출지별'] == local_name]
    
    ## 전출지별 컬럼제거 전입지별 행인덱스로 설정
    df = df.drop(columns='전출지별').set_index('전입지별')
    
    ## 전국, 서울 특별시 제외한 나머지
    df.drop(index=df.index[[0,local_idx]], inplace=True)
    
    return df

# getLocalDF('서울특별시', 1)

           1970    1971   1972    1973    1974    1975    1976    1977  \
전입지별
부산광역시     11568   11130  11768   16307   22220   27515   23732   27213
대구광역시         0       0      0       0       0       0       0       0
인천광역시         0       0      0       0       0       0       0       0
광주광역시         0       0      0       0       0       0       0       0
대전광역시         0       0      0       0       0       0       0       0
울산광역시         0       0      0       0       0       0       0       0
세종특별자치시       0       0      0       0       0       0       0       0
경기도      130149  150313  93333  143234  149045  253705  202276  207722
강원도        9352   12885  13561   16481   15479   27837   25927   25415
충청북도       6700    9457  10853   12617   11786   21073   18029   17478
충청남도      15954   18943  23406   27139   25509   51205   41447   43993
전라북도      10814   13192  16583   18642   16647   34411   29835   28444
전라남도      10513   16755  20157   22160   21314   46610   46251   43430
경상북도      11868   16459  22073   27531   26902   46177   40376   41155
경상남도       8409   10001  11263   15193   16771   23150   22400   27393
제주특별자치도    1039    1325   1617    2456    2261    3440    3623    3551

           1978    1979  ...    2008    2009    2010    2011    2012    2013  \
전입지별                     ...
부산광역시     29856   28542  ...   17353   17738   17418   18816   16135   16153
대구광역시         0       0  ...    9720   10464   10277   10397   10135   10631
인천광역시         0       0  ...   50493   45392   46082   51641   49640   47424
광주광역시         0       0  ...   10846   11725   11095   10587   10154    9129
대전광역시         0       0  ...   13515   13632   13819   13900   14080   13440
울산광역시         0       0  ...    5057    4845    4742    5188    5691    5542
세종특별자치시       0       0  ...       0       0       0       0    2998    2851
경기도      237684  278411  ...  412408  398282  410735  373771  354135  340801
강원도       26700   27599  ...   23668   23331   22736   23624   22332   20601
충청북도      18420   20047  ...   15294   15295   15461   15318   14555   13783
충청남도      48091   45388  ...   27458   24889   24522   24723   22269   21486
전라북도      29676   31570  ...   18390   18332   17569   17755   16120   14909
전라남도      44624   47934  ...   16601   17468   16429   15974   14765   14187
경상북도      42940   43565  ...   15425   16569   16042   15818   15191   14420
경상남도      28697   30183  ...   15438   15303   15689   16039   14474   14447
제주특별자치도    3937    4261  ...    5473    5332    5714    6133    6954    7828

           2014    2015    2016    2017
전입지별
부산광역시     17320   17009   15062   14484
대구광역시     10062   10191    9623    8891
인천광역시     43212   44915   43745   40485
광주광역시      9759    9216    8354    7932
대전광역시     13403   13453   12619   11815
울산광역시      6047    5950    5102    4260
세종특별자치시    6481    7550    5943    5813
경기도      332785  359337  370760  342433
강원도       21173   22659   21590   21016
충청북도      14244   14379   14087   13302
충청남도      21473   22299   21741   21020
전라북도      14566   14835   13835   13179
전라남도      14591   14598   13065   12426
경상북도      14456   15113   14236   12464
경상남도      14799   15220   13717   12692
제주특별자치도    9031   10434   10465   10404

[16 rows x 48 columns]

,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
전입지별,,,,,,,,,,,,,,,,,,,,,
부산광역시,11568,11130,11768,16307,22220,27515,23732,27213,29856,28542,...,17353,17738,17418,18816,16135,16153,17320,17009,15062,14484
대구광역시,0,0,0,0,0,0,0,0,0,0,...,9720,10464,10277,10397,10135,10631,10062,10191,9623,8891
인천광역시,0,0,0,0,0,0,0,0,0,0,...,50493,45392,46082,51641,49640,47424,43212,44915,43745,40485
광주광역시,0,0,0,0,0,0,0,0,0,0,...,10846,11725,11095,10587,10154,9129,9759,9216,8354,7932
대전광역시,0,0,0,0,0,0,0,0,0,0,...,13515,13632,13819,13900,14080,13440,13403,13453,12619,11815
울산광역시,0,0,0,0,0,0,0,0,0,0,...,5057,4845,4742,5188,5691,5542,6047,5950,5102,4260
세종특별자치시,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,2998,2851,6481,7550,5943,5813
경기도,130149,150313,93333,143234,149045,253705,202276,207722,237684,278411,...,412408,398282,410735,373771,354135,340801,332785,359337,370760,342433
강원도,9352,12885,13561,16481,15479,27837,25927,25415,26700,27599,...,23668,23331,22736,23624,22332,20601,21173,22659,21590,21016
충청북도,6700,9457,10853,12617,11786,21073,18029,17478,18420,20047,...,15294,15295,15461,15318,14555,13783,14244,14379,14087,13302
충청남도,15954,18943,23406,27139,25509,51205,41447,43993,48091,45388,...,27458,24889,24522,24723,22269,21486,21473,22299,21741,21020
전라북도,10814,13192,16583,18642,16647,34411,29835,28444,29676,31570,...,18390,18332,17569,17755,16120,14909,14566,14835,13835,13179
전라남도,10513,16755,20157,22160,21314,46610,46251,43430,44624,47934,...,16601,17468,16429,15974,14765,14187,14591,14598,13065,12426
경상북도,11868,16459,22073,27531,26902,46177,40376,41155,42940,43565,...,15425,16569,16042,15818,15191,14420,14456,15113,14236,12464
경상남도,8409,10001,11263,15193,16771,23150,22400,27393,28697,30183,...,15438,15303,15689,16039,14474,14447,14799,15220,13717,12692
제주특별자치도,1039,1325,1617,2456,2261,3440,3623,3551,3937,4261,...,5473,5332,5714,6133,6954,7828,9031,10434,10465,10404

In [56]:
## 서울특별시 관련 데이터만 추출
df1 = getLocalDF('서울특별시', 1)
display(df1)

           1970    1971   1972    1973    1974    1975    1976    1977  \
전입지별
부산광역시     11568   11130  11768   16307   22220   27515   23732   27213
대구광역시         0       0      0       0       0       0       0       0
인천광역시         0       0      0       0       0       0       0       0
광주광역시         0       0      0       0       0       0       0       0
대전광역시         0       0      0       0       0       0       0       0
울산광역시         0       0      0       0       0       0       0       0
세종특별자치시       0       0      0       0       0       0       0       0
경기도      130149  150313  93333  143234  149045  253705  202276  207722
강원도        9352   12885  13561   16481   15479   27837   25927   25415
충청북도       6700    9457  10853   12617   11786   21073   18029   17478
충청남도      15954   18943  23406   27139   25509   51205   41447   43993
전라북도      10814   13192  16583   18642   16647   34411   29835   28444
전라남도      10513   16755  20157   22160   21314   46610   46251   43430
경상북도      11868   16459  22073   27531   26902   46177   40376   41155
경상남도       8409   10001  11263   15193   16771   23150   22400   27393
제주특별자치도    1039    1325   1617    2456    2261    3440    3623    3551

           1978    1979  ...    2008    2009    2010    2011    2012    2013  \
전입지별                     ...
부산광역시     29856   28542  ...   17353   17738   17418   18816   16135   16153
대구광역시         0       0  ...    9720   10464   10277   10397   10135   10631
인천광역시         0       0  ...   50493   45392   46082   51641   49640   47424
광주광역시         0       0  ...   10846   11725   11095   10587   10154    9129
대전광역시         0       0  ...   13515   13632   13819   13900   14080   13440
울산광역시         0       0  ...    5057    4845    4742    5188    5691    5542
세종특별자치시       0       0  ...       0       0       0       0    2998    2851
경기도      237684  278411  ...  412408  398282  410735  373771  354135  340801
강원도       26700   27599  ...   23668   23331   22736   23624   22332   20601
충청북도      18420   20047  ...   15294   15295   15461   15318   14555   13783
충청남도      48091   45388  ...   27458   24889   24522   24723   22269   21486
전라북도      29676   31570  ...   18390   18332   17569   17755   16120   14909
전라남도      44624   47934  ...   16601   17468   16429   15974   14765   14187
경상북도      42940   43565  ...   15425   16569   16042   15818   15191   14420
경상남도      28697   30183  ...   15438   15303   15689   16039   14474   14447
제주특별자치도    3937    4261  ...    5473    5332    5714    6133    6954    7828

           2014    2015    2016    2017
전입지별
부산광역시     17320   17009   15062   14484
대구광역시     10062   10191    9623    8891
인천광역시     43212   44915   43745   40485
광주광역시      9759    9216    8354    7932
대전광역시     13403   13453   12619   11815
울산광역시      6047    5950    5102    4260
세종특별자치시    6481    7550    5943    5813
경기도      332785  359337  370760  342433
강원도       21173   22659   21590   21016
충청북도      14244   14379   14087   13302
충청남도      21473   22299   21741   21020
전라북도      14566   14835   13835   13179
전라남도      14591   14598   13065   12426
경상북도      14456   15113   14236   12464
경상남도      14799   15220   13717   12692
제주특별자치도    9031   10434   10465   10404

[16 rows x 48 columns]

,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
전입지별,,,,,,,,,,,,,,,,,,,,,
부산광역시,11568,11130,11768,16307,22220,27515,23732,27213,29856,28542,...,17353,17738,17418,18816,16135,16153,17320,17009,15062,14484
대구광역시,0,0,0,0,0,0,0,0,0,0,...,9720,10464,10277,10397,10135,10631,10062,10191,9623,8891
인천광역시,0,0,0,0,0,0,0,0,0,0,...,50493,45392,46082,51641,49640,47424,43212,44915,43745,40485
광주광역시,0,0,0,0,0,0,0,0,0,0,...,10846,11725,11095,10587,10154,9129,9759,9216,8354,7932
대전광역시,0,0,0,0,0,0,0,0,0,0,...,13515,13632,13819,13900,14080,13440,13403,13453,12619,11815
울산광역시,0,0,0,0,0,0,0,0,0,0,...,5057,4845,4742,5188,5691,5542,6047,5950,5102,4260
세종특별자치시,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,2998,2851,6481,7550,5943,5813
경기도,130149,150313,93333,143234,149045,253705,202276,207722,237684,278411,...,412408,398282,410735,373771,354135,340801,332785,359337,370760,342433
강원도,9352,12885,13561,16481,15479,27837,25927,25415,26700,27599,...,23668,23331,22736,23624,22332,20601,21173,22659,21590,21016
충청북도,6700,9457,10853,12617,11786,21073,18029,17478,18420,20047,...,15294,15295,15461,15318,14555,13783,14244,14379,14087,13302
충청남도,15954,18943,23406,27139,25509,51205,41447,43993,48091,45388,...,27458,24889,24522,24723,22269,21486,21473,22299,21741,21020
전라북도,10814,13192,16583,18642,16647,34411,29835,28444,29676,31570,...,18390,18332,17569,17755,16120,14909,14566,14835,13835,13179
전라남도,10513,16755,20157,22160,21314,46610,46251,43430,44624,47934,...,16601,17468,16429,15974,14765,14187,14591,14598,13065,12426
경상북도,11868,16459,22073,27531,26902,46177,40376,41155,42940,43565,...,15425,16569,16042,15818,15191,14420,14456,15113,14236,12464
경상남도,8409,10001,11263,15193,16771,23150,22400,27393,28697,30183,...,15438,15303,15689,16039,14474,14447,14799,15220,13717,12692
제주특별자치도,1039,1325,1617,2456,2261,3440,3623,3551,3937,4261,...,5473,5332,5714,6133,6954,7828,9031,10434,10465,10404

In [57]:
## 대구광역시 관련 데이터만 추출
df2 = getLocalDF('대구광역시', 3)
display(df2)

        1970 1971 1972 1973 1974 1975 1976 1977 1978 1979  ...   2008   2009  \
전입지별                                                       ...
서울특별시      0    0    0    0    0    0    0    0    0    0  ...  14824  15469
부산광역시      0    0    0    0    0    0    0    0    0    0  ...   5066   5207
인천광역시      0    0    0    0    0    0    0    0    0    0  ...   2125   2003
광주광역시      0    0    0    0    0    0    0    0    0    0  ...    563    624
대전광역시      0    0    0    0    0    0    0    0    0    0  ...   2106   2057
울산광역시      0    0    0    0    0    0    0    0    0    0  ...   4283   3740
세종특별자치시    0    0    0    0    0    0    0    0    0    0  ...      0      0
경기도        0    0    0    0    0    0    0    0    0    0  ...  13724  14534
강원도        0    0    0    0    0    0    0    0    0    0  ...   1996   1942
충청북도       0    0    0    0    0    0    0    0    0    0  ...   1762   1880
충청남도       0    0    0    0    0    0    0    0    0    0  ...   2717   2579
전라북도       0    0    0    0    0    0    0    0    0    0  ...    970    935
전라남도       0    0    0    0    0    0    0    0    0    0  ...    904   1012
경상북도       0    0    0    0    0    0    0    0    0    0  ...  48562  49288
경상남도       0    0    0    0    0    0    0    0    0    0  ...  11343  10599
제주특별자치도    0    0    0    0    0    0    0    0    0    0  ...    618    664

          2010   2011   2012   2013   2014   2015   2016   2017
전입지별
서울특별시    13915  13310  13838  13673  13735  13038  12802  13011
부산광역시     5050   4906   5216   5543   6157   5182   4860   4840
인천광역시     1968   2000   1979   2202   2015   1987   1962   1930
광주광역시      527    577    711    622    902    629    547    515
대전광역시     1956   2063   2144   2219   2254   2085   1949   1978
울산광역시     3551   3586   3844   3833   3835   3675   3266   2604
세종특별자치시      0      0    261    233    526    879    642    827
경기도      14596  13320  13581  13659  12813  12322  11918  12354
강원도       2039   1843   1807   1820   1884   1884   1748   1657
충청북도      1784   1849   1943   1958   2026   1957   1771   1824
충청남도      2730   2647   2706   2599   2682   2509   2323   2578
전라북도       860   1003    878    985    996    940    920    911
전라남도       985    947    977    948    985    953    907    897
경상북도     47895  49300  44922  45035  51852  46900  41444  41714
경상남도      9521   8821   8965   8941   9374   8922   8313   7704
제주특별자치도    631    643    773    847   1061   1317   1394   1631

[16 rows x 48 columns]

,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
전입지별,,,,,,,,,,,,,,,,,,,,,
서울특별시,0,0,0,0,0,0,0,0,0,0,...,14824,15469,13915,13310,13838,13673,13735,13038,12802,13011
부산광역시,0,0,0,0,0,0,0,0,0,0,...,5066,5207,5050,4906,5216,5543,6157,5182,4860,4840
인천광역시,0,0,0,0,0,0,0,0,0,0,...,2125,2003,1968,2000,1979,2202,2015,1987,1962,1930
광주광역시,0,0,0,0,0,0,0,0,0,0,...,563,624,527,577,711,622,902,629,547,515
대전광역시,0,0,0,0,0,0,0,0,0,0,...,2106,2057,1956,2063,2144,2219,2254,2085,1949,1978
울산광역시,0,0,0,0,0,0,0,0,0,0,...,4283,3740,3551,3586,3844,3833,3835,3675,3266,2604
세종특별자치시,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,261,233,526,879,642,827
경기도,0,0,0,0,0,0,0,0,0,0,...,13724,14534,14596,13320,13581,13659,12813,12322,11918,12354
강원도,0,0,0,0,0,0,0,0,0,0,...,1996,1942,2039,1843,1807,1820,1884,1884,1748,1657
충청북도,0,0,0,0,0,0,0,0,0,0,...,1762,1880,1784,1849,1943,1958,2026,1957,1771,1824
충청남도,0,0,0,0,0,0,0,0,0,0,...,2717,2579,2730,2647,2706,2599,2682,2509,2323,2578
전라북도,0,0,0,0,0,0,0,0,0,0,...,970,935,860,1003,878,985,996,940,920,911
전라남도,0,0,0,0,0,0,0,0,0,0,...,904,1012,985,947,977,948,985,953,907,897
경상북도,0,0,0,0,0,0,0,0,0,0,...,48562,49288,47895,49300,44922,45035,51852,46900,41444,41714
경상남도,0,0,0,0,0,0,0,0,0,0,...,11343,10599,9521,8821,8965,8941,9374,8922,8313,7704
제주특별자치도,0,0,0,0,0,0,0,0,0,0,...,618,664,631,643,773,847,1061,1317,1394,1631

In [58]:
for label_idx in seoulDF.index :
    plt.plot(seoulDF.loc[labe_idx], label=label_index)
plt.legend()
plt.tight_layout()
plt.title('서울 => 타지역 이주 현황')
plt.xticks(rotation=90)
plt.show()

NameError: name 'seoulDF' is not defined